name: "03-02 Hello World - Espocia"

on:
  workflow_dispatch:

jobs:
  say-hello-inline-bash:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Hello world from inline bash script in a Github Action Workflow! - Espocia"

