name: "03-04 Triggering Events!"

on:
  push:
    branches:
      - "example-branch/*"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

    paths:
      - "03-core-features/filter/*.md"
      - "03-core-features/filter/*.txt"

  schedule:
    - cron: "0 0 * * *" # Midnight

  workflow_dispatch:
    
jobs:
  echo-event:
    runs-on: ubuntu-24.04
    steps:
      - name: Dump full event JSON
        run: |
          echo "=== $GITHUB_EVENT_NAME payload ==="
          cat "$GITHUB_EVENT_PATH"

